export const ADD_TOKEN_INFO = 'ADD_TOKEN_INFO';
export const SAVE_TOKEN_INFO = 'SAVE_TOKEN_INFO';
export const UPDATE_TOKEN_INFO = 'UPDATE_TOKEN_INFO';
export const DELETE_TOKEN_INFO = 'DELETE_TOKEN_INFO';
